### ISSUE TITLE
cookie has some problems

### ISSUE THREAD

**Issue by ChaseWindYoungs** [vandalvnl/storage-manager-js#12]
In cookie，
const value = encodeURIComponent(JSON.stringify(object));

i want set a cookie's value，value's type is string , JSON.stringfy allways change value to "xx", then encodeURIComponent will set it to %22xx%22, value is changed

**Comment by g4rcez** [comment]
Thanks for your report.

For strings the values ​​will be set without any conversion algorithm, just the clean string
