### ISSUE TITLE
Error building app with Vite

### ISSUE THREAD

**Issue by danis039** [vandalvnl/storage-manager-js#35]
When building a React app using the latest `vite` version (5.1.3) and `storage-manager-js` >= 4.2.4:
```
Error: [commonjs--resolver] Failed to resolve entry for package "storage-manager-js". The package may have incorrect main/module/exports specified in its package.json.
```

The issue does not occur in versions prior to 4.2.4.

**Comment by HanzCEO** [comment]
I can't seem to reproduce this issue. My vite is `^5.1.4` and my storage-manager-js is `^4.2.6-5`

**Comment by g4rcez** [comment]
Hi @danis039 can you post more about this error? Maybe a side project that have this problem
