### ISSUE TITLE
SessionStorage.has() is a question 

### ISSUE THREAD

**Issue by Yee1014** [vandalvnl/storage-manager-js#4]
## Code
https://github.com/g4rcez/storage-manager-js/blob/07aaa85c98427a685ee086af8f6cd509772fa6c8/src/storages/session-storage.ts#L5

## In the console
![image](https://user-images.githubusercontent.com/19262889/102189780-1cbba780-3ef2-11eb-9740-461871bf7a7d.png)

Please check the question!

**Comment by g4rcez** [comment]
Thank you @Yee1014  for your report. I work to solve this bug

**Comment by g4rcez** [comment]
Bug fix in [session-storage.test.js](https://github.com/g4rcez/storage-manager-js/blob/master/tests/session-storage.test.js)
